### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by phodal** [phodal/mole#4]
## Tasks

Note View
- [x] Read
- [x] Create
- [x] Edit
- [ ] Note Sync

Idea View
- [x] Read
- [x] Create

Setting View
- [x] GitHub Repo Setting
- [x] GitHub Token Setting
## Tech Tasks
- [x] Cordova Package Script
- [ ] Electron Package Script
- [x] GitHub Page Deploy Script
- [ ] Travis CI Setup
- [ ] Test Env Setup
